services:
  web:
    build:
      context: ./services/web
    depends_on:
      - server
    networks:
      - messenger

  server:
    build:
      context: ./services/server
    depends_on:
      - postgres
      - redis
    networks:
      - messenger

  nginx:
    image: nginx:1.27.1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - web
      - server
    networks:
      - messenger

  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=messenger
      - POSTGRES_PASSWORD=vHawk81kua6nTwk5G3
      - POSTGRES_DB=messenger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - messenger

  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    networks:
      - messenger

networks:
  messenger:

volumes:
  postgres_data:
